### ISSUE TITLE
Add hover text for cucumber status types

### ISSUE THREAD

**Issue by TylerHaigh** [yachr/yachr#29]
As a User
I want to be able to hover my mouse over the Failed / Undefined / Pending / Passed / Ambiguous statuses in the HTML report
So that I can understand the definition of each status

**Comment by DesHorsley** [comment]
This needs the two chartjs charts in the `src\templates\standard.html` file upated to include the charts label as a hover text

**Comment by DesHorsley** [comment]
Added an info icon to the stats table explaining the order of preference of the statuses.
