### ISSUE TITLE
Summaries from Aggregator don't show feature or scenario roll ups

### ISSUE THREAD

**Issue by DesHorsley** [yachr/yachr#4]
On the generated report it would be nice to see a summary of the Features, as well as a summary of the scenarios. I don't think we'd need to go further than that.

Currently as the `ReportAggregator.getSummaryForFeature` produces a rolled up summary of the steps.

Ideally we'd have a rolled up summary of the Features, and the Scenarios.

This should give a good indication of the progress of the project, or its current status. 

I don't think it would hurt to leave the steps scenario there, it may be used in custom html reports?

**Comment by TylerHaigh** [comment]
@DesHorsley How do these changes sound to you?
